from keyboards.client_kb import kb_client_main
from keyboards.client_kb import kb_client_hospitals_answer
from keyboards.client_kb import kb_client_complete_or_replay
from keyboards.client_kb import kb_web
